### ISSUE TITLE
Farmbot?

### ISSUE THREAD

**Issue by samuk** [precision-sustainable-ag/BenchBot-ImageRepository#1]
I guess you're aware of https://farm.bot/ just curious why you didn't use it to move your camera?

**Comment by marialauracangiano** [comment]
Hi! Very late response. This is a product that we are developing as a tool for our projects but also for the purpose of the tool itself. The main difference with the farmbot is that ours is not limited to working on a bench, it has wheels which allow you to move the bot around from one bench to the other and you don't even need a bench specifically. You can do long runs and cover a big area with just starting the program once. Right now we are on phase two of the development, full automation, at this point our bot moves in the y and x directions fully on its own. Besides, the range in plant size that you are able to scan with our bot seems to be bigger from what I'm seeing on the videos on their website. We are working on a project right now where we are collecting images with a high resolution camera of plants from seedling to 60 cm tall (+pot ~ 90 cm). I love the farmbot and their UI is amazing and seems so easy to use, that's on out list of to dos still. With all that said I see our product as more versatile in some regards but we still have a long way to go to get to the level of 'user friendliness' of the farmbot. We'll be making public a confluence page with all the new updates soon and we'll link it to this repo, please stay in touch if you are interested on BenchBot.

**Comment by samuk** [comment]
Sounds good! 

You might find https://github.com/linorobot/linorobot2

Or some of my BOM here: https://github.com/samuk/Sawppy_Rover/blob/main/modifications/Ag/4x4.md#bom-provisonal interesting as you move to full autonomy.

I'll watch your project with interest.
