### ISSUE TITLE
Integrate oak-d camera with current setup

### ISSUE THREAD

**Issue by marialauracangiano** [precision-sustainable-ag/BenchBot-ImageRepository#11]

**Comment by priyajakhar** [comment]
Code-wise the oak-d was successfully integrated with the current gui. But the mounting system still needs to be figured out.

**Comment by marialauracangiano** [comment]
Jack has an option for the camera mount. I'll take some pictures today and share

**Comment by marialauracangiano** [comment]
I created a new branch from develop and added the new GUI.py script and the new requirements.txt since we want to test those today
