### ISSUE TITLE
request: reorganize repo to remove unused folders and make strucutre more intuitive

### ISSUE THREAD

**Issue by mkutu** [precision-sustainable-ag/BenchBot-ImageRepository#14]
I don't mean to overstep and feel free to ignore, but I was wondering if someone could reorganize the repo? 
The biggest benefit of cleaning things up a bit is that it reduces the potential for mistakes during debugging and general development. As it stands now, there's a lot of folders and subfolders, scripts, and content that aren't being used. Probably mostly as legacy scripts and content from using the benchbot for the opencv competition? As of now, it looks a little bit like something I'd structure in google drive which probably makes sense for the nature of the OpenCv competition. But I feel this repo has changed to specializing into a purely software dev repo, which is cool. This repo is the software for the BenchBot which really only includes the GUI, object_avoidance, and altered version of the camera SDK. 

Some specific suggestions include:

**WARNING**: restructuring might cause things to break and scripts may need to be changed. <ins>**BUT**</ins> , decluttering, while it may require a little work up front, will reduce debugging headaches and make general dev easier for everyone.

1. Removing unused folders to reduce clutter. Some folders that I have yet seen used:
    * `Hardware and structure`
    * `Images`
    * `Software (could be archived)?`
    * `Video collection`

2. Restructure main laptop gui as:
`/BenchBot/GUI` eliminating "Laptop setup"

3. Move and rename `/BenchBot/Laptop setup/object avoidance` to:
`/BenchBot/object_avoidance`
A directory name without a space, I think will make things a little easier to call things from inside that folder. While we aren't calling anything now from that directory, we may in the future and something as simple as removing a space could reduce head-aches.

```Python
#does not work because of the space in `object avoidance`
from object avoidance.some_scipt import some_class 

# I think you would have to use something like:
object_avoidance = __import__("object avoidance") #but this is bad because it acts differently, its bad style or not "pythonic", and longer and harder to read
from object_avoidance.some_script import some_class
```

```Python
# instead this is easier to read and act the way we want it
from object_avoidance.some_scipt import some_class
```

4. Move main requirements file to:
`/BenchBot/requirements.txt`
These requirements are needed for everything, not just GUI.

5. Include .gitignore file at `BenchBot/.gitignore`: 
What is [.gitignore](https://www.atlassian.com/git/tutorials/saving-changes/gitignore)?
For example, would solve extra `.vs` and `__pychache__` folder in GUI

6. Move content of current `/BenchBot/README.md` to confluence

7.  Create README.md for `GUI` and place in `BenchBot/README.md`

Of course making changes in a new branch, testing, making a PR, and merging into `develop` or `master`.

**Comment by MathewAaron** [comment]
I can help with refactoring the code and directories if required.

**Comment by marialauracangiano** [comment]
Just seeing this. We are actually working now on cleaning this repo. I agree with all the above. Thanks for all the suggestions!
