### ISSUE TITLE
Anticipated minimum ground clearance 

### ISSUE THREAD

**Issue by MathewAaron** [precision-sustainable-ag/BenchBot-ImageRepository#19]
I am exploring methods for the line following pipeline. One method is using light sensors to give additional info that the bot is off track ( along with vision ).
Since the working range for the light sensors are 5mm to 8mm from the ground (for maximum accuracy). I want to open a discussion on what would be the minimum ground clearance we would have on an uneven surface like the fields.

**Comment by marialauracangiano** [comment]
8mm from the ground seems low considering that we may have uneven terrain sometimes. Any thoughts @mtfunder?

**Comment by mtfunder** [comment]
I agree that level of ground clearance is too low for almost any surface
actually, even concrete will have larger than 3mm variations over a 1-2 ft
distance.
