### ISSUE TITLE
GUI requirements

### ISSUE THREAD

**Issue by screberg** [precision-sustainable-ag/BenchBot-ImageRepository#2]
Thanks so much for the awesome work on the GUI.  We are trying to improve our practices on the hardware projects and we need to use requirement.txt files to help all the teams replicate the GUI.  Can you run this on your laptop?

 ```-m pip freeze > requirements.txt```

If you include that file in the repository, we'll be able to build this hopefully.

**Comment by priyajakhar** [comment]
Added the requirements file to the same directory as GUI file, I am not totally sure about the dependencies though

**Comment by screberg** [comment]
Sorry to be slow getting back to this.  That was perfect and all we needed.  The dependencies themselves do not need to be in the repo, just the list is perfect.  Thanks for all the work on documentation.  Looking great.
