### ISSUE TITLE
config setup

### ISSUE THREAD

**Issue by mkutu** [precision-sustainable-ag/BenchBot-ImageRepository#21]
Moving the disscussion from pull request "PyQT5" to an issue

> It would be good to create a new folder with this version since the GUI.py here will always be different if you are using just a pi than if you are using a pi and a laptop. Unless I'm confused here and the version you have should work with any setup in which case we don't need the extra folder. I have you as a member of the repo so I'm not sure why you can't just create a new branch there.

@marialauracangiano this is an old comment from when I was not a member of the repo.  

Thanks for your suggestions. I'm happy to do what you've suggested. But may I suggest an additional option? 

Using a configuration file helps resolve a lot of the "hard coded" constant through the code base, pretty much all of [these](https://github.com/precision-sustainable-ag/BenchBot-SonyHRCam/blob/27597d07f5dbd6f700b6048a32943d0dd9c45a01/Laptop%20setup/GUI/GUI.py#L52-L66) and it avoids having to manually enter env variable in the command line that you can't see. I think, @priyajakhar correct me if I'm wrong, this is what you're doing [here](https://github.com/precision-sustainable-ag/BenchBot-SonyHRCam/blob/27597d07f5dbd6f700b6048a32943d0dd9c45a01/Laptop%20setup/GUI/GUI.py#L27-L39). 

I'm suggesting doing something very similar, but instead of writing everything in the command line, create a separate file, `configuration.yaml`, that has all [this information](https://github.com/precision-sustainable-ag/BenchBot-SonyHRCam/blob/27597d07f5dbd6f700b6048a32943d0dd9c45a01/Laptop%20setup/GUI/GUI.py#L27-L66) in a single location and can be easily read by people (and your code) for debugging and changing. Then coordinating your scripts through a single `main.py` file.

There are various ways you can setup a your configuration. We use a tool called Hydra which is way overkill for this. But it uses a `.yaml` file which is very easy to read (unlike a json dictionary or command line variable inputs). A `main.py` makes things more _object-oriented_ which is a system design paradigm that breaks things into smaller pieces thus making them easier to debug. Debugging i think is a primary focus since we are, and will be in future, integrating multiple pieces of hard-ware and software across various user-levels.

Option 2:
1. Create a single configuration file that keep all your hard-coded variables, plus an option to run with RPi or with a laptop, in a single location.
2. Make a `main.py` script that coordinates your overall system including `GUI.py`  and pull the configuration file into that `main.py`.
 
Some pseudo code would look something like this:

## config.yaml

```YAML
ROBOT_LENGTH: some number
ROBOT_WIDTH: some number
PI_USERNAME: your username
PI_PASSWORD: your password
DISTANCE_TRAVELED: some number
WHEEL_MOTORS: some numbers
NUMBER_OF_SENSORS: some number
# and 
SETUP_TYPE: RPi  # or Laptop

```

## main.py
```Python
# main.py
import GUI
import sensor_server
import yaml

with open('config.yaml') as f:
    config = yaml.load(f, Loader=yaml.FullLoader)

ROBOT_LENGTH =config["ROBOT_LENGTH "]
# width of the robot (distance between two front wheels) in cm
ROBOT_WIDTH = config["ROBOT_WIDTH "]
# if you haven't changed your pi's name the default username is 'pi'
PI_USERNAME = config["PI_USERNAME "]
# if you haven't changed your pi's password, the default is 'raspberrypi'
PI_PASSWORD = config["PI_PASSWORD "]
# Distance between rows in mm
DISTANCE_TRAVELED = int(config["DISTANCE_TRAVELED "]])
# if BB moving backwards change the motors order to [3,2]
WHEEL_MOTORS = list(map(int,config["WHEEL_MOTORS "].split(',')))
# number of ultrasonic sensors on the robot
NUMBER_OF_SENSORS = int(config["NUMBER_OF_SENSORS "])

# and
SETUP_TYPE = config["setup_type"]

if SETUP_TYPE  == "RPi":
    start sensor server
    """(make slight tweaks in GUI that allow for 2 different setups. This is as simple as a single if/else statement. 2 lines of code.)"""
    start GUI 
    
if SETUP_TYPE  == "Laptop":
    start GUI (same)
    Do other stuff that's needed for laptop setup

```

_Originally posted by @mkutu in https://github.com/precision-sustainable-ag/BenchBot-SonyHRCam/issues/4#issuecomment-1229096561_

**Comment by marialauracangiano** [comment]
Regarding the question of the "hard coded" constants. Each site should have a .env file where these variables are stored, as we have it setup now, since these vary per site. The .env file looks a lot like the config.yaml file that you are suggesting (I don't have one in my laptop but Jack can share ours with you as an example). Could you explain what the differences would be between those two? In principle they seem to fulfill the same purpose.
I agree about having everything in one main file and being able to switch depending on SETUP_TYPE.

**Comment by mkutu** [comment]
@marialauracangiano I see now. Thanks for explaining that. Yes, sounds like the `.env` file does the same thing. 
However, the `.env` is hidden because of the `.` before the file name and folks won't easily see it. I also didn't see it in the repo. but understand its a work in progress.

Personally, I like the yaml format because it's visually easy to read especially for folks not used to reading code. But I haven't seen the text file and I'm probably splitting hairs.

**Comment by marialauracangiano** [comment]
Yea. We need to add a .env example in the repo so it's not confusing. It's actually a pretty simple file, very similar to the example that you provided above. 
Regarding the main.py, yes, I think it's a god idea to set it up in that way since we need to simplify this as much as possible for potential external users. And for us, too. It's more organized in that way.

**Comment by marialauracangiano** [comment]
This is the .env file at MD. We'll need to include here the SETUP_TYPE

### .env

``` python
# Length of the robot (between front and back sensors) measured in cm
ROBOT_LENGTH = 133
# width of the robot (distance between two front wheels) in cm
ROBOT_WIDTH = 215
# if you haven't changed your pi's name the default username is 'pi'
PI_USERNAME = 'pi_username'
# if you haven't changed your pi's password, the default should be 'raspberry'
PI_PASSWORD = 'pi_password'
# Distance between rows in mm
DISTANCE_TRAVELED = 400
# if BB moving backwards change the motors order to [3,2]
WHEEL_MOTORS = '3,2'
# number of ultrasonic sensors on the robot
NUMBER_OF_SENSORS = 2
# the trigger pins for sensors
TRIGGER_PINS = '23,17'
# the echo pins for sensors
ECHO_PINS = '18,4'
# reverse to move backwards or forwards
DIRECTIONS = 'negative,positive'
HOME_TO_END_SENSOR_DISTANCE = 1000
```
