### ISSUE TITLE
Check which image didn't get captured on a row and go back to that stop to retake the image

### ISSUE THREAD

**Issue by marialauracangiano** [precision-sustainable-ag/BenchBot-ImageRepository#22]
See if possible or if it makes sense to:

- Save the timestamp to reuse it for the new image (Necessary?).

**Comment by priyajakhar** [comment]
Updates in development:

- Logic for recapturing the entire row once if any images were missed is written and tested on benchbot
- Same timestamp is being used to capture sony and oak-d images
- The images from each camera are being stored in their respective folders inside the main images folder
- pseudo logic for recapturing missed images is in progress

Need some clarification on below points:

- suppose 4 images are to be captured in a row, what if images at 1 or 2 places were missed, do we need to recapture all of them? the logic will get a little complicated for recapturing more than one instances of missed images
- where should the camera plate move after recapturing? let's suppose image was missed at position 1 (think of indices, for 4 images we have 0,1,2,3 stops), the camera plate will move to position 1 and recapture image, so to save time it makes sense to move the camera plate to that end of the bot. But what if we recaptured image at position 2 or 3, then same logic wouldn't work. Should I include logic to move camera plate to nearest end of the bot? again it complicates the code

Contact me for more clarification if needed.

**Comment by priyajakhar** [comment]
The GUI was updated to include the feature of capturing the missed images in a row. The way it works is

- A first round of capturing images happens for a row
- During this process, under the image rename function, we keep a record of which images were successfully found in the folder following an image capture procedure completion
- At the end of a row, we check the list of captured images to see if we missed any
- If no images were missed, the bot proceeds to the next row
- If images were missed, the bot checks the list to see exactly where the images got missed
- It goes to each spot and recaptures the images, after which the camera plate is moved to either of the closer ends on the bot
- Then the bot proceeds to the next row, the check for missed images in a row only happens once to prevent any major delays in the entire process

Current logic only checks for missed .JPG images from the SONY camera, it can be further improved upon to also check for missed .ARW images from SONY and the missed .png images from OAK-D camera.

The issue can be closed upon successful merge of the feature branch.

**Comment by priyajakhar** [comment]
feature branch was successfully merged into develop
